apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    orgId: 1
    access: proxy
    url: http://victoriametrics:8428
    isDefault: false
    editable: false
    basicAuth: true
    basicAuthUser: ${VM_AUTH_USERNAME}
    jsonData:
      httpMethod: POST
    secureJsonData:
      basicAuthPassword: ${VM_AUTH_PASSWORD}
